services:
  - type: web
    name: niky-debut
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: PORT
        value: 10000

